# These are supported funding model platforms

github: phkaiser13

patreon: phkaiser13

open_collective: laramara


ko_fi: amaorgbr


tidelift: npm/amaorgbr


community_bridge: fnpeti

liberapay: oncb

issuehunt: fnpeti
lfx_crowdfunding: laramara

polar: amaorgbr

buy_me_a_coffee: fnpeti

thanks_dev: oncb

custom:
  - https://fundacaodorina.org.br/doe
  - https://www.abads.org.br/doe
  - https://livredetrabalhoinfantil.org.br/doe
  - https://www.adeva.org.br/doe
