github: phkaiser13

patreon: phkaiser13

open_collective: laramara

custom:
  # Organizações brasileiras
  - https://www.ibc.gov.br/doe                   # Instituto Benjamin Constant (deficiência visual)
  - https://www.apaebrasil.org.br/doe           # APAE (deficiências múltiplas)
  - https://www.abraautismo.org.br/doe          # ABRA (autismo)
  - https://www.fundabrinq.org.br/doe           # Fundação Abrinq (crianças e adolescentes)
  - https://www.institutorodrigomendes.org.br/doe # Instituto Rodrigo Mendes (inclusão de pessoas com deficiência)
  - https://fundacaodorina.org.br/doe           # Fundação Dorina Nowill (deficiência visual)
  - https://www.abads.org.br/doe                # ABADS (deficiência e inclusão)
  - https://livredetrabalhoinfantil.org.br/doe  # Combate ao trabalho infantil
  - https://www.adeva.org.br/doe                # Associação de Deficientes Visuais do Amazonas

  # Organizações globais
  - https://www.worldblindunion.org/donate       # World Blind Union
  - https://www.autismspeaks.org/donate          # Autism Speaks
  - https://www.savethechildren.org/donate      # Save the Children (trabalho infantil)
  - https://www.hi.org/en/donate                 # Humanity & Inclusion (deficiências)
  - https://www.rnib.org.uk/donate               # RNIB (deficiência visual)
