[package]
name = "trackiellm-security"
version = "1.0.0"
edition = "2021"
authors = ["Pedro Henrique <phdev13@example.com>"]
description = "Security module for TrackieLLM - provides key management, encryption, and secure channels"
license = "AGPL-3.0"
repository = "https://github.com/example/trackiellm"

[lib]
name = "trackiellm_security"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies for basic functionality
libc = "0.2"
thiserror = "1.0"

# Optional dependencies for enhanced functionality
# Note: These would be enabled based on target platform and features
sodiumoxide = { version = "0.2", optional = true }
ring = { version = "0.17", optional = true }
rand = { version = "0.8", optional = true }
zeroize = { version = "1.7", features = ["zeroize_derive"], optional = true }
sha2 = { version = "0.10", optional = true }
hex = { version = "0.4", optional = true }

[dev-dependencies]
# Dependencies for testing
tempfile = "3.0"

[features]
default = ["ring_crypto"]

# Basic crypto using simple hash-based key derivation (current implementation)
basic_crypto = []

# Enhanced crypto using libsodium through sodiumoxide
enhanced_crypto = ["sodiumoxide"]

# Alternative crypto using ring
ring_crypto = ["ring", "rand", "zeroize", "sha2", "hex"]

# Enable all security features
full_security = ["enhanced_crypto", "ring_crypto"]

# Development and testing features
dev_mode = []
test_vectors = []

[build-dependencies]
# Build script dependencies if needed
cc = "1.0"

# Profile optimizations
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
panic = "unwind"

# Metadata for C integration
[package.metadata.capi]
header_name = "trackiellm_security"
include_guard = "TRACKIELLM_SECURITY_H"
min_version = "1.0.0"

[package.metadata.capi.header]
name = "trackiellm_security"
subdirectory = "security"
generation = true
enabled = true

[package.metadata.capi.pkg_config]
name = "trackiellm-security"
description = "Security module for TrackieLLM"
filename = "trackiellm-security"
version = "1.0.0"

# Documentation
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# Platform-specific configurations
[target.'cfg(target_os = "linux")'.dependencies]
# Linux-specific dependencies

[target.'cfg(target_os = "macos")'.dependencies]
# macOS-specific dependencies

[target.'cfg(target_os = "windows")'.dependencies]
# Windows-specific dependencies

[target.'cfg(target_arch = "aarch64")'.dependencies]
# ARM64-specific dependencies

[target.'cfg(target_arch = "x86_64")'.dependencies]
# x86_64-specific dependencies