# This file will be populated in the next step.
# Creating it now to establish the directory structure.
name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set up C/C++ build environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Set up C/C++ build environment (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake ninja

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build

    - name: Run tests (if any)
      working-directory: ./build
      run: ctest -C Release --output-on-failure
